name: 'GitHub Action for Yarn'
description: 'Wraps the yarn CLI to enable common yarn commands'
author: 'Alex Bordun'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  cmd:
    description: 'Yarn command'
    required: true
  dir:
    description: 'Yarn sub-folder (if needed)'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
