name: 'GitHub Action for Yarn'
description: 'Wraps the yarn CLI to enable common yarn commands'
author: 'Alex Bordun'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  cmd:
    description: 'Yarn command'
    required: true
#  auth-token:
#    description: 'NPM_AUTH_TOKEN'
#  registry-url:
#    description: 'NPM_REGISTRY_URL'
runs:
  using: 'node16'
  main: 'dist/index.js'
#  env:
#    NPM_AUTH_TOKEN: ${{ inputs.auth-token }}
#    NPM_REGISTRY_URL: ${{ inputs.registry-url }}
